/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check da API */
        get: operations["e3e9f0e2c5f769c480b4fc3eb71344c0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registar conta */
        post: operations["e98c1f4ee213264ef4e8d43951b8a856"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sessão */
        post: operations["5e8e2c5b0676bd70d4fc876066c11089"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da sessão */
        get: operations["956294a5368a0297085338e6c53a3a22"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Terminar sessão */
        post: operations["c027d15455fed1d1de059c632932cfc7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar pedidos do condutor */
        get: operations["91c0a2669ff7a96c6c4645720597763e"];
        put?: never;
        /** Criar pedido de SOS */
        post: operations["49267325d7e61bbb5ebbf91605614f00"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pedidos disponíveis para prestador */
        get: operations["3577f8cc9d797c90bbbfb7976a96ba43"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de um pedido */
        get: operations["54728e248cd506b642793d5584a32707"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar estado do pedido */
        put: operations["047297920c375ef6ecac28bacada1177"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar veículos do condutor */
        get: operations["821c6d9675af95657af9e3d7364b4449"];
        put?: never;
        /** Registar veículo */
        post: operations["674b77cf923570874ee89ab2a14f6f4b"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/{id}/principal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Definir veículo principal */
        put: operations["04ebbab044ee42f637702b3803e82188"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prestadores próximos (público) */
        get: operations["fae5551ba556022ef2bc02ba98d62cd3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil completo do prestador */
        get: operations["0c42150b392ad9b6ff682700e1ddd28c"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Alterar disponibilidade (online/offline) */
        put: operations["43ef4d714724f5e4d763fc2420ccd5b5"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serviços do prestador */
        get: operations["5043e3f68185568f3fcb22c742d9a88a"];
        put?: never;
        /** Criar serviço */
        post: operations["28adfa62b6587c8b6ff00a748f1e13da"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documentos do prestador */
        get: operations["f37c736f1146c9354b254bd4d6a2cbcf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/verification/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submeter verificação */
        post: operations["e8bbb795d5c22b683774de15f3c9a187"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ganhos do prestador */
        get: operations["9e63f3cef17ae87bfad4372a37f784f2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estatísticas globais */
        get: operations["eba3ca322c007fef18ce5a3e907c984e"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar condutores */
        get: operations["43334f95d2b2d5880009c26a62a06240"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/professionals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar prestadores */
        get: operations["51889d1b944f942e3936360ebb5be034"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/professionals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de um prestador */
        get: operations["0972cf60cab025e8d98ba8f976151c11"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/professionals/{id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Decidir verificação */
        put: operations["dccae72c6b23650e47845872ad27d320"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/documents/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Aprovar/rejeitar documento */
        put: operations["abdcc8780a77035bbb72e05da78f669a"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os pedidos */
        get: operations["d41aa1247f830bac4aead7380c239f35"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar promoções */
        get: operations["d5990e77bb6d694c1cecd918108dfe69"];
        put?: never;
        /** Criar promoção */
        post: operations["36ce4a52e5c7877a3d4c2188d1aa514f"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar configurações */
        put: operations["702acdc25c3c4b7f51b9778c42babee1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registo de ações do administrador */
        get: operations["7eebe7d7ce808688c1168cb8948119fc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            error: string;
            /** @description Código normalizado (ex: VALIDATION) */
            code?: string;
            details?: Record<string, never> | null;
        };
        AuthResponse: {
            /** @description JWT */
            token: string;
            user: components["schemas"]["User"];
        };
        Professional: components["schemas"]["User"] & {
            distancia_km?: number | null;
            numero_servicos?: number;
        };
        Service: {
            id: number;
            provider_id: number;
            category_id: number;
            nome: string;
            descricao?: string | null;
            preco: number;
        };
        SosRequest: {
            id: number;
            numero_req: string;
            user_id: number;
            provider_id?: number | null;
            category_id?: number;
            vehicle_id?: number | null;
            /** @enum {string} */
            status: "procurando" | "aceite" | "em_andamento" | "concluido" | "cancelado";
            descricao?: string | null;
            latitude: number;
            longitude: number;
            endereco?: string | null;
            valor?: number | null;
        };
        User: {
            id: number;
            nome: string;
            email: string;
            telefone: string;
            /** @enum {string} */
            role: "condutor" | "prestador" | "admin";
            avatar?: string | null;
            estado?: string;
            estado_profissional?: string | null;
            latitude?: number | null;
            longitude?: number | null;
        };
        Vehicle: {
            id: number;
            placa: string;
            marca: string;
            modelo: string;
            cor?: string | null;
            tipo?: string | null;
            ano?: number | null;
            foto?: string | null;
            principal?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    e3e9f0e2c5f769c480b4fc3eb71344c0: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serviço saudável */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    e98c1f4ee213264ef4e8d43951b8a856: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome: string;
                    /** Format: email */
                    email: string;
                    telefone: string;
                    /** Format: password */
                    password: string;
                    /** @enum {string} */
                    role: "condutor" | "prestador";
                };
            };
        };
        responses: {
            /** @description Conta criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validação falhou */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "5e8e2c5b0676bd70d4fc876066c11089": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E-mail ou telefone */
                    identificador: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Sessão iniciada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "956294a5368a0297085338e6c53a3a22": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utilizador autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    c027d15455fed1d1de059c632932cfc7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão terminada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "91c0a2669ff7a96c6c4645720597763e": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de pedidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SosRequest"][];
                };
            };
        };
    };
    "49267325d7e61bbb5ebbf91605614f00": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    category_id: number;
                    vehicle_id?: number | null;
                    /** @description Prestador escolhido diretamente */
                    provider_id?: number | null;
                    descricao?: string | null;
                    latitude: number;
                    longitude: number;
                    endereco?: string | null;
                };
            };
        };
        responses: {
            /** @description Pedido criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SosRequest"];
                };
            };
            /** @description Validação falhou */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "3577f8cc9d797c90bbbfb7976a96ba43": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de pedidos disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "54728e248cd506b642793d5584a32707": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pedido completo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pedido não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "047297920c375ef6ecac28bacada1177": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "aceite" | "em_andamento" | "concluido" | "cancelado";
                    observacao?: string | null;
                    /** @description Obrigatório ao concluir */
                    valor?: number | null;
                };
            };
        };
        responses: {
            /** @description Estado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transição de estado inválida */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "821c6d9675af95657af9e3d7364b4449": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de veículos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
        };
    };
    "674b77cf923570874ee89ab2a14f6f4b": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    placa: string;
                    marca: string;
                    modelo: string;
                    cor?: string | null;
                    tipo?: string | null;
                    ano?: number | null;
                    /** @default false */
                    principal?: boolean;
                };
            };
        };
        responses: {
            /** @description Veículo criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Matrícula duplicada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "04ebbab044ee42f637702b3803e82188": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Veículo principal atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fae5551ba556022ef2bc02ba98d62cd3: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                raio?: number;
                categoria?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de profissionais */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Professional"][];
                };
            };
        };
    };
    "0c42150b392ad9b6ff682700e1ddd28c": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil com serviços, documentos, reviews e ganhos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "43ef4d714724f5e4d763fc2420ccd5b5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "online" | "offline";
                };
            };
        };
        responses: {
            /** @description Disponibilidade atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conta não verificada */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "5043e3f68185568f3fcb22c742d9a88a": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de serviços do prestador */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "28adfa62b6587c8b6ff00a748f1e13da": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    category_id: number;
                    nome: string;
                    descricao?: string | null;
                    preco: number;
                };
            };
        };
        responses: {
            /** @description Serviço criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
        };
    };
    f37c736f1146c9354b254bd4d6a2cbcf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de documentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    e8bbb795d5c22b683774de15f3c9a187: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verificação submetida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Já verificada ou em análise */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "9e63f3cef17ae87bfad4372a37f784f2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ganhos, série mensal e serviços de hoje */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eba3ca322c007fef18ce5a3e907c984e: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estatísticas da plataforma */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "43334f95d2b2d5880009c26a62a06240": {
        parameters: {
            query?: {
                estado?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de condutores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "51889d1b944f942e3936360ebb5be034": {
        parameters: {
            query?: {
                estado?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de prestadores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "0972cf60cab025e8d98ba8f976151c11": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil administrativo completo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dccae72c6b23650e47845872ad27d320: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    estado: "verificado" | "rejeitado" | "pendente_verificacao";
                    /** @description Obrigatório ao rejeitar */
                    motivo?: string | null;
                };
            };
        };
        responses: {
            /** @description Verificação atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Documentos obrigatórios não verificados */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    abdcc8780a77035bbb72e05da78f669a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documento atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    d41aa1247f830bac4aead7380c239f35: {
        parameters: {
            query?: {
                estado?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de pedidos com nomes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    d5990e77bb6d694c1cecd918108dfe69: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de promoções */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "36ce4a52e5c7877a3d4c2188d1aa514f": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    titulo: string;
                    descricao?: string | null;
                    codigo?: string | null;
                    percentual?: number | null;
                    /** @default true */
                    ativo?: boolean;
                };
            };
        };
        responses: {
            /** @description Promoção criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "702acdc25c3c4b7f51b9778c42babee1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configurações atualizadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "7eebe7d7ce808688c1168cb8948119fc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
